In [1]:
import torch

In [17]:
t = torch.Tensor([[0.12,-0.3], 
                  [-0.9, 0.4], 
                  [0.5, -0.23]])

In [18]:
t

tensor([[ 0.1200, -0.3000],
        [-0.9000,  0.4000],
        [ 0.5000, -0.2300]])

In [8]:
t.shape

torch.Size([3, 2])

In [21]:
torch.softmax(t, dim=1)

tensor([[0.6035, 0.3965],
        [0.2142, 0.7858],
        [0.6748, 0.3252]])

In [12]:
torch.argmax(t, dim=1)

tensor([0, 1, 0])

In [16]:
type(t.numpy())

numpy.ndarray